services:
  - type: web
    name: herramienta-de-campo
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: ASSET_ID
        sync: false
      - key: API_TOKEN
        sync: false
      - key: NOMBRE_PROYECTO
        value: Encuesta Cantonal Machala 2026
      - key: CAMPO_ENCUESTADOR
        value: C_digo_encuestador
      - key: CAMPO_SUPERVISOR
        value: C_digo_Supervisor
      - key: META_ENCUESTAS
        value: 2500
      - key: CACHE_TTL_SEGUNDOS
        value: 90
