services:
  - type: web
    name: herramienta-de-campo
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: ASSET_ID_PICHINCHA
        sync: false
      - key: API_TOKEN
        sync: false
      - key: NOMBRE_PROYECTO
        value: Encuesta Pichincha 2026
      - key: CAMPO_ENCUESTADOR
        value: cenc
      - key: CAMPO_SUPERVISOR
        value: csup
      - key: META_ENCUESTAS
        value: 1600
      - key: CACHE_TTL_SEGUNDOS
        value: 90
