services:
  - type: web
    name: encuestascs3
    env: node
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: ASSET_ID
        sync: false
      - key: API_TOKEN
        sync: false
      - key: NOMBRE_PROYECTO
        value: Encuesta Cantonal Otavalo 2026
      - key: CAMPO_ENCUESTADOR
        value: cenc
      - key: CAMPO_SUPERVISOR
        value: csup
      - key: META_ENCUESTAS
        value: 500
      - key: CACHE_TTL_SEGUNDOS
        value: 90
